# You can have multiple ini files if you want, it doesn't matter.
[HyoukaFrameGen]
Name=Hyouka Frame Generation (Experimental)
Author=Hyouka
Fragment=hyouka_framegen.fsh
Vertex=fxaa.vsh
60fps=True
UsePreviousFrame=True
SettingName1=Motion strength
SettingDefaultValue1=0.5
SettingMaxValue1=1.0
SettingMinValue1=0.0
SettingStep1=0.05

[FXAA]
Name=FXAA Antialiasing
Author=nVidia
Fragment=fxaa.fsh
Vertex=fxaa.vsh
